// Code generated by extwiki.  DO NOT EDIT.

package wikipedia

var extractedTitles = [...]string{
	"Coat of arms of Andorra",
	"Coat of arms of Germany",
	"Dubravka (drama)",
	"Eurovision Song Contest",
	"Glagolitic script",
	"Nikola Tesla",
	"Royal cypher",
}
