((go-ts-mode . ((comment-start . "/* ")
                (comment-end . " */")
                (comment-continue . "   ")
                (require-final-newline . t)))
 (mhtml-mode . ((fill-column . 79))))